[package]
name = "embedded-test-example"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/probe-rs/embedded-test-example"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
esp-println = { version="0.7.1", features = ["log", "rtt", "esp32c6", "colors"], default-features = false }
esp32c6-hal = { version="0.6.0" }
log = "0.4.20"

[dev-dependencies]
embedded-test = {git="https://github.com/probe-rs/embedded-test", features = ["log"]}
panic-probe = {git = "https://github.com/t-moe/defmt", features = ["print-rtt"]}  # the upstream create does not support riscv yet

[[test]]
name = "example_test"
harness = false
