[package]
name = "embedded-test-example"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/probe-rs/embedded-test-example"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
esp32c6-hal = { version="0.6.0" }

# dependencies when using the log feature
esp-println = { version="0.7.1", features = ["log", "rtt", "esp32c6", "colors"], default-features = false, optional = true}
log = { version = "0.4.20", optional = true}

# dependencies when using the demft feature
defmt = { version = "0.3.5", optional = true }
defmt-rtt = { version = "0.4.0", optional = true }

[dev-dependencies]
embedded-test = {git="https://github.com/probe-rs/embedded-test"}
panic-probe = {git = "https://github.com/t-moe/defmt", features = ["print-rtt"]}  # the upstream create does not support riscv yet

[features]
default = ["log"]
log = ["dep:esp-println", "dep:log", "embedded-test/log"]
defmt = ["dep:defmt-rtt", "dep:defmt", "embedded-test/defmt"] # Adapt .cargo/config when enabling this feature

[[test]]
name = "example_test"
harness = false
