[package]
name = "embedded-test-example"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/probe-rs/embedded-test-example"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
esp32c6-hal = { version="0.6.0" }

# dependencies when using the log feature
esp-println = { version="0.7.1", features = ["log", "rtt", "esp32c6", "colors"], default-features = false, optional = true}
log = { version = "0.4.20", optional = true}

# dependencies when using the demft feature
defmt = { version = "0.3.5", optional = true }
defmt-rtt = { version = "0.4.0", optional = true }

[dev-dependencies]
embedded-test = {version="0.2.2", features = ["embassy"]}

panic-probe = {git = "https://github.com/t-moe/defmt"}  # the upstream create does not use semihosting yet
# Note: You need to provide your own exception handler, as panic_probe no longer provides this

embassy-executor = { default-features = false, version="0.4.0", features = ["executor-thread", "arch-riscv32"] }
# Note: You need to enable at least one executor feature on embassy

[patch.crates-io] # Patch defmt globally, as it is a native library.
defmt = { git = "https://github.com/t-moe/defmt" }
defmt-rtt = { git = "https://github.com/t-moe/defmt" }

[features]
default = ["log"]
log = ["dep:esp-println", "dep:log", "embedded-test/log", "panic-probe/print-rtt"]
defmt = ["dep:defmt-rtt", "dep:defmt", "embedded-test/defmt", "panic-probe/print-defmt"]
# Note: You must adapt .cargo/config when enabling the defmt feature

[[test]]
name = "example_test"
harness = false
